#!/usr/bin/env bash
# Create a branch, commit, push, and open a PR for a blog post.

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <post-file> <title>" >&2
    echo "" >&2
    echo "Example: $0 blog/2026-03-15-docparse-cloud-api.md \"DocParse: Cloud API Launch\"" >&2
    exit 1
fi

POST="$1"
TITLE="$2"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BLOG_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

# Resolve post path
if [[ -f "$BLOG_ROOT/$POST" ]]; then
    POST_PATH="$BLOG_ROOT/$POST"
    POST_REL="$POST"
elif [[ -f "$POST" ]]; then
    POST_PATH="$POST"
    POST_REL=$(realpath --relative-to="$BLOG_ROOT" "$POST")
else
    echo "ERROR: File not found: $POST" >&2
    exit 1
fi

cd "$BLOG_ROOT"

# Determine format from tags
IS_PRESS=$(grep -c "press-release" "$POST_PATH" 2>/dev/null || true)
if [[ "$IS_PRESS" -gt 0 ]]; then
    FORMAT="press-release"
else
    FORMAT="product-launch"
fi

# Extract slug from filename
FILENAME=$(basename "$POST_PATH" .md)
SLUG=$(echo "$FILENAME" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//')
BRANCH="blog/${FORMAT}-${SLUG}"

# Extract product tag from frontmatter
PRODUCT_TAG=$(sed -n '/^tags:/p' "$POST_PATH" | grep -o '\b[a-z-]*\b' | grep -v "product-launch\|press-release\|tags" | head -1 || echo "unknown")

echo "=== Publishing Blog Post ==="
echo "Post: $POST_REL"
echo "Title: $TITLE"
echo "Format: $FORMAT"
echo "Branch: $BRANCH"
echo "Product: $PRODUCT_TAG"
echo ""

# 1. Create branch
echo "1/4 Creating branch..."
if git rev-parse --verify "$BRANCH" > /dev/null 2>&1; then
    echo "  Branch $BRANCH already exists, switching to it"
    git checkout "$BRANCH"
else
    git checkout -b "$BRANCH"
    echo "  ✓ Created branch: $BRANCH"
fi

# 2. Stage and commit
echo ""
echo "2/4 Staging and committing..."
git add "$POST_REL"
# Also stage any images referenced in the post
for img in $(grep -o 'img/[^ )]*' "$POST_PATH" 2>/dev/null | sort -u); do
    IMG_PATH="blog/$img"
    if [[ -f "$BLOG_ROOT/$IMG_PATH" ]]; then
        git add "$IMG_PATH"
        echo "  + staged image: $IMG_PATH"
    fi
done

git commit -m "Add $FORMAT: $TITLE"
echo "  ✓ Committed"

# 3. Push
echo ""
echo "3/4 Pushing..."
git push -u origin "$BRANCH"
echo "  ✓ Pushed to origin/$BRANCH"

# 4. Create PR
echo ""
echo "4/4 Creating PR..."
PR_BODY="## $(echo "$FORMAT" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

- **Product:** $PRODUCT_TAG
- **Author:** Solaris (AI)
- **Format:** $(echo "$FORMAT" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')
- **Post:** $POST_REL

### Pre-merge checklist
- [ ] Content reviewed by human editor
- [ ] Banner image added (if missing)
- [ ] Links verified
- [ ] Tone and accuracy checked
$(if [[ "$IS_PRESS" -gt 0 ]]; then echo "- [ ] Quote attributed correctly"; fi)

---
Generated by the product-launch skill."

PR_URL=$(gh pr create --title "Blog: $TITLE" --body "$PR_BODY" 2>&1)
echo "  ✓ PR created: $PR_URL"

echo ""
echo "=== Done ==="
echo "POST_PATH: $POST_REL"
echo "PR_URL: $PR_URL"
echo "BRANCH_NAME: $BRANCH"
